package phpmyadmin

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// WriteConfig generates config.inc.php wired to local MySQL.
func WriteConfig(pmaPath string, mysqlPort int) error {
	if mysqlPort <= 0 {
		mysqlPort = 3306
	}
	secret, err := blowfishSecret(32)
	if err != nil {
		return err
	}

	// Preserve existing blowfish_secret when regenerating (e.g. port change).
	cfgPath := filepath.Join(pmaPath, "config.inc.php")
	if existing, err := os.ReadFile(cfgPath); err == nil {
		if m := reBlowfish.FindSubmatch(existing); len(m) >= 2 && len(m[1]) >= 32 {
			secret = string(m[1])
		}
	}

	body := fmt.Sprintf(`<?php
/**
 * Generated by Larahan — do not edit manually.
 * Credentials match Larahan MySQL (root / empty password).
 */
declare(strict_types=1);

$cfg['blowfish_secret'] = '%s';

$i = 0;
$i++;
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['host'] = '127.0.0.1';
$cfg['Servers'][$i]['port'] = '%d';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';
$cfg['Servers'][$i]['AllowNoPassword'] = true;
$cfg['Servers'][$i]['extension'] = 'mysqli';

$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
$cfg['TempDir'] = '%s';
`, secret, mysqlPort, filepath.ToSlash(filepath.Join(pmaPath, "tmp")))

	tmpDir := filepath.Join(pmaPath, "tmp")
	if err := os.MkdirAll(tmpDir, 0o755); err != nil {
		return err
	}
	return os.WriteFile(cfgPath, []byte(body), 0o644)
}

var reBlowfish = regexp.MustCompile(`\$cfg\['blowfish_secret'\]\s*=\s*'([^']+)'`)

func blowfishSecret(n int) (string, error) {
	buf := make([]byte, n)
	if _, err := rand.Read(buf); err != nil {
		return "", err
	}
	return hex.EncodeToString(buf), nil
}

// DetectVersion reads phpMyAdmin version from Version.php when available.
func DetectVersion(pmaPath string) string {
	candidates := []string{
		filepath.Join(pmaPath, "libraries", "classes", "Version.php"),
		filepath.Join(pmaPath, "package.json"),
	}
	rePHP := regexp.MustCompile(`VERSION\s*=\s*'([^']+)'`)
	reJSON := regexp.MustCompile(`"version"\s*:\s*"([^"]+)"`)
	for _, path := range candidates {
		data, err := os.ReadFile(path)
		if err != nil {
			continue
		}
		text := string(data)
		if strings.HasSuffix(path, ".php") {
			if m := rePHP.FindStringSubmatch(text); len(m) >= 2 {
				return m[1]
			}
		}
		if m := reJSON.FindStringSubmatch(text); len(m) >= 2 {
			return m[1]
		}
	}
	return defaultVersion
}
