// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppInfo describes the Larahan application itself.
 */
export interface AppInfo {
    "name": string;
    "version": string;
    "description": string;
}

/**
 * ComponentInfo is shared across Dashboard / Apache / PHP / MySQL views.
 */
export interface ComponentInfo {
    "type": ComponentType;
    "version": string;
    "status": ComponentStatus;
    "path": string;
    "installed": boolean;
}

/**
 * ComponentStatus describes the runtime state of a stack component.
 */
export enum ComponentStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusNotInstalled = "not_installed",
    StatusStopped = "stopped",
    StatusRunning = "running",
    StatusReady = "ready",
    StatusError = "error",
    StatusInstalling = "installing",
};

/**
 * ComponentType identifies a managed package kind.
 */
export enum ComponentType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TypeApache = "apache",
    TypePHP = "php",
    TypeMySQL = "mysql",
    TypePhpMyAdmin = "phpmyadmin",
};

/**
 * DashboardSummary is the Dashboard overview payload.
 */
export interface DashboardSummary {
    "apache": ComponentInfo;
    "mysql": ComponentInfo;
    "active_php": string;
    "php": ComponentInfo;
    "phpmyadmin": ComponentInfo;
}

/**
 * DownloadProgress is emitted during package download.
 */
export interface DownloadProgress {
    "type": string;
    "version": string;
    "percent": number;
    "bytes": number;
    "total": number;
    "cached": boolean;
    "filename": string;
}

/**
 * ExtensionStatus is the install/enable state of a PHP library.
 */
export enum ExtensionStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ExtEnabled = "enabled",
    ExtDisabled = "disabled",
    ExtNotInstalled = "not_installed",
};

/**
 * InstallErrorEvent is emitted when the install pipeline fails.
 */
export interface InstallErrorEvent {
    "type": string;
    "version": string;
    "message": string;
}

/**
 * InstallStage identifies a step in the install pipeline.
 */
export enum InstallStage {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StageDownload = "download",
    StageVerify = "verify",
    StageExtract = "extract",
    StageConfigure = "configure",
    StageDone = "done",
};

/**
 * InstallStageEvent is emitted when the install pipeline changes stage.
 */
export interface InstallStageEvent {
    "type": string;
    "version": string;
    "stage": InstallStage;
    "message": string;
}

/**
 * LibrarySummary is the Library module payload.
 */
export interface LibrarySummary {
    "installed": boolean;
    "php_version": string;
    "php_path": string;
    "apache_running": boolean;
    "message": string;
    "extensions": PHPExtension[] | null;
}

/**
 * PHPExtension describes one PHP library/extension.
 */
export interface PHPExtension {
    "name": string;
    "display_name": string;
    "status": ExtensionStatus;
    "version": string;
    "dll": string;
    "builtin": boolean;
    "zend": boolean;
    "toggleable": boolean;
}

/**
 * PHPVersionInfo describes one supported PHP version entry.
 */
export interface PHPVersionInfo {
    "version": string;
    "installed": boolean;
    "active": boolean;
    "path": string;
}

/**
 * Paths lists standard Larahan directories under the install root.
 */
export interface Paths {
    "root": string;
    "apache": string;
    "php": string;
    "mysql": string;
    "phpmyadmin": string;
    "downloads": string;
    "logs": string;
    "config": string;
    "temp": string;
}

/**
 * Result is a generic operation response for the frontend.
 */
export interface Result {
    "ok": boolean;
    "message": string;
}

/**
 * Settings holds runtime configuration persisted as JSON.
 */
export interface Settings {
    "install_path": string;
    "active_php": string;
    "apache_port": number;
    "mysql_port": number;
    "first_run": boolean;
}
