// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ApacheService exposes Apache management to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * GetInfo returns Apache version, status, and install path.
 */
export function GetInfo(): $CancellablePromise<models$0.ComponentInfo> {
    return $Call.ByID(2038668610);
}

/**
 * Install starts async Apache package install + auto configure.
 */
export function Install(): $CancellablePromise<models$0.Result> {
    return $Call.ByID(3487054325);
}

/**
 * Restart restarts Apache.
 */
export function Restart(): $CancellablePromise<models$0.Result> {
    return $Call.ByID(2667503441);
}

/**
 * Start launches Apache.
 */
export function Start(): $CancellablePromise<models$0.Result> {
    return $Call.ByID(3463447390);
}

/**
 * Stop stops Apache.
 */
export function Stop(): $CancellablePromise<models$0.Result> {
    return $Call.ByID(872050278);
}

/**
 * Uninstall stops and removes Apache.
 */
export function Uninstall(): $CancellablePromise<models$0.Result> {
    return $Call.ByID(5790216);
}
