// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DashboardService exposes environment summary to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * GetSummary returns current Apache, MySQL, and PHP overview.
 */
export function GetSummary(): $CancellablePromise<models$0.DashboardSummary> {
    return $Call.ByID(1792487102);
}

/**
 * RestartAll restarts Apache and MySQL.
 */
export function RestartAll(): $CancellablePromise<models$0.Result> {
    return $Call.ByID(2430083280);
}

/**
 * StartAll starts Apache and MySQL.
 */
export function StartAll(): $CancellablePromise<models$0.Result> {
    return $Call.ByID(3218961845);
}

/**
 * StopAll stops Apache and MySQL.
 */
export function StopAll(): $CancellablePromise<models$0.Result> {
    return $Call.ByID(2032114701);
}
