// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LibraryService exposes PHP extension management to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * Disable turns off a PHP extension in php.ini.
 */
export function Disable(name: string): $CancellablePromise<models$0.Result> {
    return $Call.ByID(346751655, name);
}

/**
 * Enable turns on a PHP extension in php.ini.
 */
export function Enable(name: string): $CancellablePromise<models$0.Result> {
    return $Call.ByID(4224034946, name);
}

/**
 * GetSummary returns PHP version and extension list for the active PHP.
 */
export function GetSummary(): $CancellablePromise<models$0.LibrarySummary> {
    return $Call.ByID(1677465525);
}
