// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MySQLService exposes MySQL management to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * GetInfo returns MySQL version, status, and install path.
 */
export function GetInfo(): $CancellablePromise<models$0.ComponentInfo> {
    return $Call.ByID(4042849736);
}

/**
 * Install starts async MySQL package install + configure + init.
 */
export function Install(): $CancellablePromise<models$0.Result> {
    return $Call.ByID(1092703803);
}

/**
 * Restart restarts MySQL.
 */
export function Restart(): $CancellablePromise<models$0.Result> {
    return $Call.ByID(1640009955);
}

/**
 * Start launches MySQL.
 */
export function Start(): $CancellablePromise<models$0.Result> {
    return $Call.ByID(3502661652);
}

/**
 * Stop stops MySQL.
 */
export function Stop(): $CancellablePromise<models$0.Result> {
    return $Call.ByID(3081686480);
}

/**
 * Uninstall stops and removes MySQL.
 */
export function Uninstall(): $CancellablePromise<models$0.Result> {
    return $Call.ByID(3347450474);
}
