// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PhpMyAdminService exposes phpMyAdmin management to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * GetInfo returns phpMyAdmin version, status, and install path.
 */
export function GetInfo(): $CancellablePromise<models$0.ComponentInfo> {
    return $Call.ByID(317700695);
}

/**
 * GetURL returns the local phpMyAdmin URL.
 */
export function GetURL(): $CancellablePromise<string> {
    return $Call.ByID(4117709748);
}

/**
 * Install starts async phpMyAdmin package install + MySQL config + Apache alias.
 */
export function Install(): $CancellablePromise<models$0.Result> {
    return $Call.ByID(1743295876);
}

/**
 * Open opens phpMyAdmin in the default browser.
 */
export function Open(): $CancellablePromise<models$0.Result> {
    return $Call.ByID(2055467325);
}

/**
 * Uninstall removes phpMyAdmin and clears the Apache alias.
 */
export function Uninstall(): $CancellablePromise<models$0.Result> {
    return $Call.ByID(1898531805);
}
