// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PHPService exposes PHP version management to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * Delete removes an installed PHP version.
 */
export function Delete(version: string): $CancellablePromise<models$0.Result> {
    return $Call.ByID(1740644909, version);
}

/**
 * GetActive returns the currently active PHP version.
 */
export function GetActive(): $CancellablePromise<string> {
    return $Call.ByID(4198863128);
}

/**
 * Install starts async download+extract for a PHP version.
 */
export function Install(version: string): $CancellablePromise<models$0.Result> {
    return $Call.ByID(2420970657, version);
}

/**
 * ListVersions returns supported PHP versions and install state.
 */
export function ListVersions(): $CancellablePromise<models$0.PHPVersionInfo[] | null> {
    return $Call.ByID(2828947699);
}

/**
 * Switch activates a PHP version and updates Apache automatically.
 */
export function Switch(version: string): $CancellablePromise<models$0.Result> {
    return $Call.ByID(1923413818, version);
}
