// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService exposes application settings to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

/**
 * Get returns current settings.
 */
export function Get(): $CancellablePromise<models$0.Settings> {
    return $Call.ByID(2097181443);
}

/**
 * GetAppInfo returns application metadata.
 */
export function GetAppInfo(): $CancellablePromise<models$0.AppInfo> {
    return $Call.ByID(19175910);
}

/**
 * GetPaths returns the standard Larahan directory layout.
 */
export function GetPaths(): $CancellablePromise<models$0.Paths> {
    return $Call.ByID(2364678421);
}

/**
 * OpenDirectory opens a Larahan directory in Windows Explorer.
 */
export function OpenDirectory(kind: string): $CancellablePromise<models$0.Result> {
    return $Call.ByID(3988998624, kind);
}

/**
 * Save persists settings and applies port changes to installed services.
 */
export function Save(settings: models$0.Settings): $CancellablePromise<models$0.Result> {
    return $Call.ByID(4205477668, settings);
}
