package apache

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

var (
	reDefineSRVROOT       = regexp.MustCompile(`(?m)^Define\s+SRVROOT\s+".*"`)
	reServerRoot          = regexp.MustCompile(`(?m)^ServerRoot\s+".*"`)
	reListen              = regexp.MustCompile(`(?m)^Listen\s+\S+`)
	reServerName          = regexp.MustCompile(`(?m)^#?ServerName\s+\S+`)
	reIncludeLarahan      = regexp.MustCompile(`(?m)^\s*Include\s+conf/extra/httpd-larahan\.conf\s*$`)
	reIncludePhpMyAdmin   = regexp.MustCompile(`(?m)^\s*Include\s+conf/extra/httpd-phpmyadmin\.conf\s*$`)
)

// stockRoots are default install paths shipped by Apache Lounge builds.
var stockRoots = []string{
	"C:/Apache24-64",
	"C:/Apache24",
	"c:/Apache24-64",
	"c:/Apache24",
	"C:\\Apache24-64",
	"C:\\Apache24",
}

// Configure writes Apache paths, listen port, and Larahan include snippet.
func Configure(apacheRoot string, port int) error {
	if err := normalizeLayout(apacheRoot); err != nil {
		return err
	}
	if port <= 0 {
		port = 80
	}
	rootSlash := filepath.ToSlash(apacheRoot)

	confPath := filepath.Join(apacheRoot, "conf", "httpd.conf")
	data, err := os.ReadFile(confPath)
	if err != nil {
		return fmt.Errorf("baca httpd.conf: %w", err)
	}
	content := rewriteInstallPaths(string(data), rootSlash)

	listenLine := fmt.Sprintf("Listen %d", port)
	if reListen.MatchString(content) {
		content = reListen.ReplaceAllString(content, listenLine)
	} else {
		content += "\n" + listenLine + "\n"
	}

	serverName := "ServerName localhost"
	if reServerName.MatchString(content) {
		content = reServerName.ReplaceAllString(content, serverName)
	} else {
		content += "\n" + serverName + "\n"
	}

	if !reIncludeLarahan.MatchString(content) {
		content = strings.TrimRight(content, "\r\n") + "\n\nInclude conf/extra/httpd-larahan.conf\n"
	}
	if !reIncludePhpMyAdmin.MatchString(content) {
		content = strings.TrimRight(content, "\r\n") + "\nInclude conf/extra/httpd-phpmyadmin.conf\n"
	}

	if err := os.WriteFile(confPath, []byte(content), 0o644); err != nil {
		return err
	}

	if err := os.MkdirAll(filepath.Join(apacheRoot, "conf", "extra"), 0o755); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Join(apacheRoot, "logs"), 0o755); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Join(apacheRoot, "htdocs"), 0o755); err != nil {
		return err
	}

	larahanConf := filepath.Join(apacheRoot, "conf", "extra", "httpd-larahan.conf")
	if _, err := os.Stat(larahanConf); os.IsNotExist(err) {
		body := `# Generated by Larahan — do not edit manually
# PHP handler is written automatically when you Switch PHP version.
`
		if err := os.WriteFile(larahanConf, []byte(body), 0o644); err != nil {
			return err
		}
	}

	pmaConf := filepath.Join(apacheRoot, "conf", "extra", "httpd-phpmyadmin.conf")
	if _, err := os.Stat(pmaConf); os.IsNotExist(err) {
		body := `# Generated by Larahan — phpMyAdmin alias is written on install.
`
		if err := os.WriteFile(pmaConf, []byte(body), 0o644); err != nil {
			return err
		}
	}

	indexPath := filepath.Join(apacheRoot, "htdocs", "index.html")
	if _, err := os.Stat(indexPath); os.IsNotExist(err) {
		html := `<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><title>Larahan</title></head>
<body>
  <h1>Larahan is running</h1>
  <p>Apache document root is ready.</p>
</body>
</html>
`
		if err := os.WriteFile(indexPath, []byte(html), 0o644); err != nil {
			return err
		}
	}

	return nil
}

// rewriteInstallPaths replaces Apache Lounge default roots and forces ServerRoot/Define.
func rewriteInstallPaths(content, rootSlash string) string {
	for _, stock := range stockRoots {
		content = strings.ReplaceAll(content, stock, rootSlash)
	}

	srvDefine := fmt.Sprintf(`Define SRVROOT "%s"`, rootSlash)
	if reDefineSRVROOT.MatchString(content) {
		content = reDefineSRVROOT.ReplaceAllString(content, srvDefine)
	} else {
		content = srvDefine + "\n" + content
	}

	srvRoot := fmt.Sprintf(`ServerRoot "%s"`, rootSlash)
	if reServerRoot.MatchString(content) {
		content = reServerRoot.ReplaceAllString(content, srvRoot)
	} else {
		content = srvDefine + "\n" + srvRoot + "\n" + content
	}

	return content
}

// normalizeLayout lifts nested Apache24/ (or similar) into the install root
// and merges any missing top-level folders from a nested tree.
func normalizeLayout(apacheRoot string) error {
	if err := liftNestedApache(apacheRoot); err != nil {
		return err
	}
	if !hasHttpd(apacheRoot) {
		return fmt.Errorf("httpd.exe tidak ditemukan di %s", apacheRoot)
	}
	if !hasHttpdConf(apacheRoot) {
		return fmt.Errorf("Apache tidak lengkap (conf/httpd.conf hilang) di %s — uninstall lalu install ulang Apache", apacheRoot)
	}
	return nil
}

// liftNestedApache merges children from a nested Apache* folder into apacheRoot.
// Existing names are kept; only missing entries are moved up.
func liftNestedApache(apacheRoot string) error {
	entries, err := os.ReadDir(apacheRoot)
	if err != nil {
		return err
	}
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		candidate := filepath.Join(apacheRoot, e.Name())
		// Nested tree is usable if it has httpd and/or a real conf tree.
		if !hasHttpd(candidate) && !hasHttpdConf(candidate) {
			continue
		}
		children, err := os.ReadDir(candidate)
		if err != nil {
			return err
		}
		for _, child := range children {
			from := filepath.Join(candidate, child.Name())
			to := filepath.Join(apacheRoot, child.Name())
			if _, err := os.Stat(to); err == nil {
				continue
			}
			if err := os.Rename(from, to); err != nil {
				return err
			}
		}
		_ = os.Remove(candidate)
		break
	}
	return nil
}

// DetectVersion runs httpd -v and parses Apache/x.y.z.
func DetectVersion(httpdExe string) string {
	out, err := runHttpd(httpdExe, "-v")
	if err != nil {
		return defaultVersion
	}
	re := regexp.MustCompile(`Apache/(\d+\.\d+(?:\.\d+)?)`)
	m := re.FindStringSubmatch(out)
	if len(m) >= 2 {
		return m[1]
	}
	return defaultVersion
}
