package apache

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/larahan/larahan/backend/process"
)

// IsApacheInstalled reports whether httpd.exe exists under the install root.
func (m *Manager) IsApacheInstalled() bool {
	return dirHasApache(m.root())
}

// IsApacheRunning reports whether httpd.exe is currently running.
func (m *Manager) IsApacheRunning() bool {
	return process.IsRunning(httpdImage)
}

// SetBeforeStart registers a hook executed before Apache starts (e.g. apply PHP).
func (m *Manager) SetBeforeStart(fn func() error) {
	m.beforeStart = fn
}

// RestartIfRunning restarts Apache only when it is currently running.
func (m *Manager) RestartIfRunning() error {
	if !process.IsRunning(httpdImage) {
		return nil
	}
	return m.Restart()
}

// ApplyPHPModule writes the PHP Apache handler into httpd-larahan.conf.
func (m *Manager) ApplyPHPModule(phpPath, version string) error {
	if !m.IsApacheInstalled() {
		return fmt.Errorf("Apache belum terinstal")
	}
	m.phpPath = phpPath
	if err := Configure(m.root(), m.port()); err != nil {
		return err
	}
	if err := WritePHPHandler(m.root(), phpPath, version); err != nil {
		return err
	}
	if out, err := m.run("-t"); err != nil {
		return fmt.Errorf("httpd config invalid setelah switch PHP: %s (%v)", out, err)
	}
	_ = ensurePHPInfoPage(filepath.Join(m.root(), "htdocs"))
	return nil
}

// WritePHPHandler regenerates conf/extra/httpd-larahan.conf for the given PHP build.
func WritePHPHandler(apacheRoot, phpPath, version string) error {
	phpSlash := filepath.ToSlash(phpPath)
	moduleDLL, tsDLL, err := resolvePHPApacheDLLs(phpPath, version)
	if err != nil {
		return err
	}
	moduleName := phpApacheModuleName(version, moduleDLL)

	var b strings.Builder
	b.WriteString("# Generated by Larahan — do not edit manually\n")
	b.WriteString(fmt.Sprintf("# Active PHP: %s\n\n", version))
	for _, dep := range phpRuntimeLoadFiles(phpPath) {
		b.WriteString(fmt.Sprintf(`LoadFile "%s/%s"`, phpSlash, dep))
		b.WriteString("\n")
	}
	b.WriteString(fmt.Sprintf(`LoadFile "%s/%s"`, phpSlash, tsDLL))
	b.WriteString("\n")
	b.WriteString(fmt.Sprintf(`LoadModule %s "%s/%s"`, moduleName, phpSlash, moduleDLL))
	b.WriteString("\n")
	b.WriteString(fmt.Sprintf(`PHPIniDir "%s"`, phpSlash))
	b.WriteString("\n\n")
	b.WriteString(`<FilesMatch \.php$>
    SetHandler application/x-httpd-php
</FilesMatch>
`)
	b.WriteString("\nDirectoryIndex index.php index.html\n")

	extraDir := filepath.Join(apacheRoot, "conf", "extra")
	if err := os.MkdirAll(extraDir, 0o755); err != nil {
		return err
	}
	path := filepath.Join(extraDir, "httpd-larahan.conf")
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

// phpApacheModuleName returns the LoadModule identifier for the PHP SAPI DLL.
// PHP 7 exports php7_module; PHP 8+ exports php_module.
func phpApacheModuleName(version, moduleDLL string) string {
	lowerDLL := strings.ToLower(moduleDLL)
	if strings.HasPrefix(lowerDLL, "php7") || strings.HasPrefix(version, "7.") {
		return "php7_module"
	}
	return "php_module"
}

func resolvePHPApacheDLLs(phpPath, version string) (moduleDLL, tsDLL string, err error) {
	entries, err := os.ReadDir(phpPath)
	if err != nil {
		return "", "", err
	}
	for _, e := range entries {
		name := strings.ToLower(e.Name())
		if strings.HasSuffix(name, "apache2_4.dll") {
			moduleDLL = e.Name()
		}
		if name == "php8ts.dll" || name == "php7ts.dll" {
			tsDLL = e.Name()
		}
	}
	if moduleDLL == "" {
		// Fallback by major version.
		if strings.HasPrefix(version, "7.") {
			moduleDLL = "php7apache2_4.dll"
		} else {
			moduleDLL = "php8apache2_4.dll"
		}
	}
	if tsDLL == "" {
		if strings.HasPrefix(version, "7.") {
			tsDLL = "php7ts.dll"
		} else {
			tsDLL = "php8ts.dll"
		}
	}
	if _, err := os.Stat(filepath.Join(phpPath, moduleDLL)); err != nil {
		return "", "", fmt.Errorf("modul Apache PHP tidak ditemukan (%s) — pastikan build Thread Safe", moduleDLL)
	}
	if _, err := os.Stat(filepath.Join(phpPath, tsDLL)); err != nil {
		return "", "", fmt.Errorf("DLL runtime PHP tidak ditemukan (%s)", tsDLL)
	}
	return moduleDLL, tsDLL, nil
}

// phpRuntimeLoadFiles lists OpenSSL/cURL (and similar) DLLs that Apache must
// LoadFile before php_curl.dll / php_openssl.dll can be loaded. Windows reports
// a missing dependency as "The specified module could not be found".
func phpRuntimeLoadFiles(phpPath string) []string {
	entries, err := os.ReadDir(phpPath)
	if err != nil {
		return nil
	}
	present := map[string]string{}
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		lower := strings.ToLower(name)
		if !strings.HasSuffix(lower, ".dll") || strings.HasPrefix(lower, "php") {
			continue
		}
		present[lower] = name
	}

	var out []string
	add := func(lower string) {
		if name, ok := present[lower]; ok {
			out = append(out, name)
			delete(present, lower)
		}
	}
	addPrefix := func(prefix string) {
		keys := make([]string, 0)
		for k := range present {
			if strings.HasPrefix(k, prefix) {
				keys = append(keys, k)
			}
		}
		sort.Strings(keys)
		for _, k := range keys {
			add(k)
		}
	}

	addPrefix("libcrypto-")
	addPrefix("libssl-")
	add("libssh2.dll")
	add("nghttp2.dll")
	add("libsodium.dll")
	add("libsqlite3.dll")
	add("libsasl.dll")
	add("libpq.dll")
	return out
}

func ensurePHPInfoPage(htdocs string) error {
	if err := os.MkdirAll(htdocs, 0o755); err != nil {
		return err
	}
	indexPHP := filepath.Join(htdocs, "index.php")
	if _, err := os.Stat(indexPHP); err == nil {
		return nil
	}
	body := `<?php
phpinfo();
`
	return os.WriteFile(indexPHP, []byte(body), 0o644)
}
