package apache

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

const phpMyAdminConfRel = `conf/extra/httpd-phpmyadmin.conf`

var reIncludePhpMyAdminLine = regexp.MustCompile(`(?m)^\s*Include\s+conf/extra/httpd-phpmyadmin\.conf\s*$`)

// WritePhpMyAdminAlias creates Apache Alias /phpmyadmin pointing at pmaPath.
func (m *Manager) WritePhpMyAdminAlias(pmaPath string) error {
	if !m.IsApacheInstalled() {
		return fmt.Errorf("Apache belum terinstal atau instalasinya tidak lengkap (httpd.conf hilang). Install ulang Apache terlebih dahulu")
	}
	if err := ensurePhpMyAdminInclude(m.root()); err != nil {
		return err
	}
	if err := writePhpMyAdminConf(m.root(), pmaPath); err != nil {
		return err
	}
	if out, err := m.run("-t"); err != nil {
		return fmt.Errorf("httpd config invalid setelah alias phpMyAdmin: %s (%v)", out, err)
	}
	return nil
}

// RemovePhpMyAdminAlias clears the phpMyAdmin Apache alias snippet.
func (m *Manager) RemovePhpMyAdminAlias() error {
	if !hasHttpd(m.root()) {
		return nil
	}
	path := filepath.Join(m.root(), filepath.FromSlash(phpMyAdminConfRel))
	body := `# Generated by Larahan — phpMyAdmin alias is written on install.
`
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil && !os.IsNotExist(err) {
		return err
	}
	return nil
}

func ensurePhpMyAdminInclude(apacheRoot string) error {
	confPath := filepath.Join(apacheRoot, "conf", "httpd.conf")
	data, err := os.ReadFile(confPath)
	if err != nil {
		return fmt.Errorf("Apache tidak lengkap (tidak bisa baca httpd.conf): %w — install ulang Apache", err)
	}
	content := string(data)
	if !reIncludePhpMyAdminLine.MatchString(content) {
		content = strings.TrimRight(content, "\r\n") + "\nInclude conf/extra/httpd-phpmyadmin.conf\n"
		if err := os.WriteFile(confPath, []byte(content), 0o644); err != nil {
			return err
		}
	}
	return os.MkdirAll(filepath.Join(apacheRoot, "conf", "extra"), 0o755)
}

func writePhpMyAdminConf(apacheRoot, pmaPath string) error {
	if err := os.MkdirAll(filepath.Join(apacheRoot, "conf", "extra"), 0o755); err != nil {
		return err
	}
	pmaSlash := filepath.ToSlash(pmaPath)
	var b strings.Builder
	b.WriteString("# Generated by Larahan — do not edit manually\n")
	b.WriteString(fmt.Sprintf("Alias /phpmyadmin \"%s\"\n", pmaSlash))
	b.WriteString(fmt.Sprintf("<Directory \"%s\">\n", pmaSlash))
	b.WriteString("    Options FollowSymLinks\n")
	b.WriteString("    AllowOverride All\n")
	b.WriteString("    Require all granted\n")
	b.WriteString("    DirectoryIndex index.php\n")
	b.WriteString("</Directory>\n")
	return os.WriteFile(filepath.Join(apacheRoot, filepath.FromSlash(phpMyAdminConfRel)), []byte(b.String()), 0o644)
}
